package org.lch.attendance.domain;

// Generated 2012-5-2 16:56:18 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Clas generated by hbm2java
 */
@Entity
public class Clas extends BaseEntity implements java.io.Serializable {

	private Integer clasId;

	private Department department;
	
	private String clasDept;

	private String clasName;

	private String clasGrade;

	private String clasDesc;

	private Set<User> users = new HashSet<User>(0);

	private Set<Week> weeks = new HashSet<Week>(0);

	public Clas() {
	}

	public Clas(String clasName, String clasGrade) {
		this.clasName = clasName;
		this.clasGrade = clasGrade;
	}

	public Clas(Department department, String clasName, String clasGrade,
			String clasDesc, Set<User> users, Set<Week> weeks) {
		this.department = department;
		this.clasName = clasName;
		this.clasGrade = clasGrade;
		this.clasDesc = clasDesc;
		this.users = users;
		this.weeks = weeks;
	}

	public Integer getClasId() {
		return this.clasId;
	}

	public void setClasId(Integer clasId) {
		this.clasId = clasId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getClasName() {
		return this.clasName;
	}

	public void setClasName(String clasName) {
		this.clasName = clasName;
	}

	public String getClasGrade() {
		return this.clasGrade;
	}

	public void setClasGrade(String clasGrade) {
		this.clasGrade = clasGrade;
	}

	public String getClasDesc() {
		return this.clasDesc;
	}

	public void setClasDesc(String clasDesc) {
		this.clasDesc = clasDesc;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Week> getWeeks() {
		return this.weeks;
	}

	public void setWeeks(Set<Week> weeks) {
		this.weeks = weeks;
	}
	@Override
	public Integer getId() {
		return this.clasId;
	}

	@Override
	public void setId(Integer id) {
		this.clasId = id;
	}

	public String getClasDept() {
		return clasDept;
	}

	public void setClasDept(String clasDept) {
		this.clasDept = clasDept;
	}
}
