package org.lch.attendance.domain;

// Generated 2012-5-2 16:56:18 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Department generated by hbm2java
 */
@Entity
public class Department extends BaseEntity implements java.io.Serializable {

	private Integer deptId;

	private String deptName;

	private String deptDesc;

	private Set<Clas> clases = new HashSet<Clas>(0);

	private Set<Week> weeks = new HashSet<Week>(0);

	public Department() {
	}

	public Department(String deptName) {
		this.deptName = deptName;
	}

	public Department(String deptName, String deptDesc, Set<Clas> clases,
			Set<Week> weeks) {
		this.deptName = deptName;
		this.deptDesc = deptDesc;
		this.clases = clases;
		this.weeks = weeks;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptDesc() {
		return this.deptDesc;
	}

	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	public Set<Clas> getClases() {
		return this.clases;
	}

	public void setClases(Set<Clas> clases) {
		this.clases = clases;
	}

	public Set<Week> getWeeks() {
		return this.weeks;
	}

	public void setWeeks(Set<Week> weeks) {
		this.weeks = weeks;
	}
	
	@Override
	public Integer getId() {
		return this.deptId;
	}

	@Override
	public void setId(Integer id) {
		this.deptId = id;
	}
}
