package org.lch.attendance.domain;

// Generated 2012-5-2 16:56:18 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Detail generated by hbm2java
 */
@Entity
public class Detail extends BaseEntity implements java.io.Serializable {

	private Integer detailId;

	private Week week;

	private Integer weekId;
	
	public Integer getWeekId() {
		if(week!=null)
			return week.getWeekId();
		else
			return weekId;
	}

	public void setWeekId(Integer weekId) {
		this.weekId = weekId;
	}

	private User user;
	private String userName;

	public String getUserName() {
		if(user!=null)
			return user.getUserName();
		else 
			return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	private Integer detailLate;

	private Integer detailEarly;

	private Integer detailAffair;

	private Integer detailIll;

	private Integer detailPub;

	private Integer detailQuit;

	private String detailClear;

	private Date detailTime;

	public Detail() {
	}

	public Detail(Week week, User user, Date detailTime) {
		this.week = week;
		this.user = user;
		this.detailTime = detailTime;
	}

	public Detail(Week week, User user, Integer detailLate,
			Integer detailEarly, Integer detailAffair, Integer detailIll,
			Integer detailPub, Integer detailQuit, String detailClear,
			Date detailTime) {
		this.week = week;
		this.user = user;
		this.detailLate = detailLate;
		this.detailEarly = detailEarly;
		this.detailAffair = detailAffair;
		this.detailIll = detailIll;
		this.detailPub = detailPub;
		this.detailQuit = detailQuit;
		this.detailClear = detailClear;
		this.detailTime = detailTime;
	}

	public Integer getDetailId() {
		return this.detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	public Week getWeek() {
		return this.week;
	}

	public void setWeek(Week week) {
		this.week = week;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getDetailLate() {
		return this.detailLate;
	}

	public void setDetailLate(Integer detailLate) {
		this.detailLate = detailLate;
	}

	public Integer getDetailEarly() {
		return this.detailEarly;
	}

	public void setDetailEarly(Integer detailEarly) {
		this.detailEarly = detailEarly;
	}

	public Integer getDetailAffair() {
		return this.detailAffair;
	}

	public void setDetailAffair(Integer detailAffair) {
		this.detailAffair = detailAffair;
	}

	public Integer getDetailIll() {
		return this.detailIll;
	}

	public void setDetailIll(Integer detailIll) {
		this.detailIll = detailIll;
	}

	public Integer getDetailPub() {
		return this.detailPub;
	}

	public void setDetailPub(Integer detailPub) {
		this.detailPub = detailPub;
	}

	public Integer getDetailQuit() {
		return this.detailQuit;
	}

	public void setDetailQuit(Integer detailQuit) {
		this.detailQuit = detailQuit;
	}

	public String getDetailClear() {
		return this.detailClear;
	}

	public void setDetailClear(String detailClear) {
		this.detailClear = detailClear;
	}

	public Date getDetailTime() {
		return this.detailTime;
	}

	public void setDetailTime(Date detailTime) {
		this.detailTime = detailTime;
	}

	@Override
	public Integer getId() {
		return detailId;
	}

	@Override
	public void setId(Integer id) {
		setDetailId(id);
	}

}
