package org.lch.attendance.domain;
// default package
// Generated 2012-5-6 21:48:14 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Leave generated by hbm2java
 */
@Entity
public class Leave extends BaseEntity implements java.io.Serializable {

	private int leaveId;

	private User userSelf;

	private User userDelegate;

	private User userTeacher;

	private String leaveInfo;
	
	private String leaveReason;

	private Date leaveTime;

	private Boolean leaveStatus;
	
	private Boolean leaveFlag;
	
	private String flagName;
	private String statusName;



	public String getFlagName() {
		if(leaveFlag)
			flagName = "已审核";
		else
			flagName = "未审核";
		return flagName;
	}

	public void setFlagName(String flagName) {
		this.flagName = flagName;
	}

	public String getStatusName() {
		if(leaveStatus)
			statusName = "已审核";
		else
			statusName = "未审核";
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	private String leaveUser;
	private String leaveClas;
	private String leaveNum;
	private String leaveDelegate;
	private String leaveTeacher;
	
	
	public String getLeaveDelegate() {
		if(userDelegate!=null)
			return userDelegate.getUserName();
		else
			return leaveDelegate;
	}

	public void setLeaveDelegate(String leaveDelegate) {
		this.leaveDelegate = leaveDelegate;
	}

	public String getLeaveTeacher() {
		if(userTeacher!=null)
			return userTeacher.getUserName();
		return leaveTeacher;
	}

	public void setLeaveTeacher(String leaveTeacher) {
		this.leaveTeacher = leaveTeacher;
	}

	public String getLeaveUser() {
		if(userSelf!=null)
			return userSelf.getUserName();
		else
			return leaveUser;
	}

	public void setLeaveUser(String leaveUser) {
		this.leaveUser = leaveUser;
	}

	public String getLeaveClas() {
		if(userSelf!=null){
			if(userSelf.getClas()!=null)
				return userSelf.getClas().getClasName();
		}
		return leaveClas;
	}

	public void setLeaveClas(String leaveClas) {
		this.leaveClas = leaveClas;
	}

	public String getLeaveNum() {
		if(userSelf!=null)
			return userSelf.getUserNum();
		else
			return leaveNum;
	}

	public void setLeaveNum(String leaveNum) {
		this.leaveNum = leaveNum;
	}

	public Leave() {
	}

	public Leave(int leaveId, User userSelf, User userDelegate, User userTeacher, String leaveInfo,
			String leaveReason, Date leaveTime) {
		this.leaveId = leaveId;
		this.userSelf = userSelf;
		this.userDelegate = userDelegate;
		this.userTeacher = userTeacher;
		this.leaveInfo = leaveInfo;
		this.leaveReason = leaveReason;
		this.leaveTime = leaveTime;
	}

	public Leave(int leaveId, User userSelf, User userDelegate, User userTeacher, String leaveInfo,
			String leaveReason, Date leaveTime, Boolean leaveStatus,Boolean leaveFlag) {
		this.leaveId = leaveId;
		this.userSelf = userSelf;
		this.userDelegate = userDelegate;
		this.userTeacher = userTeacher;
		this.leaveInfo = leaveInfo;
		this.leaveReason = leaveReason;
		this.leaveTime = leaveTime;
		this.leaveStatus = leaveStatus;
		this.leaveFlag = leaveFlag;
	}

	public int getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(int leaveId) {
		this.leaveId = leaveId;
	}

	public String getLeaveReason() {
		return this.leaveReason;
	}

	public void setLeaveReason(String leaveReason) {
		this.leaveReason = leaveReason;
	}

	public Date getLeaveTime() {
		return this.leaveTime;
	}

	public void setLeaveTime(Date leaveTime) {
		this.leaveTime = leaveTime;
	}

	public User getUserSelf() {
		return userSelf;
	}

	public void setUserSelf(User userSelf) {
		this.userSelf = userSelf;
	}

	public User getUserDelegate() {
		return userDelegate;
	}

	public void setUserDelegate(User userDelegate) {
		this.userDelegate = userDelegate;
	}

	public User getUserTeacher() {
		return userTeacher;
	}

	public void setUserTeacher(User userTeacher) {
		this.userTeacher = userTeacher;
	}

	public Boolean getLeaveStatus() {
		return leaveStatus;
	}

	public void setLeaveStatus(Boolean leaveStatus) {
		this.leaveStatus = leaveStatus;
	}

	public Boolean getLeaveFlag() {
		return leaveFlag;
	}

	public void setLeaveFlag(Boolean leaveFlag) {
		this.leaveFlag = leaveFlag;
	}

	public String getLeaveInfo() {
		return leaveInfo;
	}

	public void setLeaveInfo(String leaveInfo) {
		this.leaveInfo = leaveInfo;
	}

	@Override
	public Integer getId() {
		return getLeaveId();
	}

	@Override
	public void setId(Integer id) {
		setLeaveId(id);
	}

}
