package org.lch.attendance.domain;
// default package
// Generated 2012-5-6 21:48:14 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Message generated by hbm2java
 */
@Entity
public class Message extends BaseEntity implements java.io.Serializable {

	private int messageId;

	private User userSender;

	private User userReceiver;

	private Boolean messageStatus;
	
	private String messageRead; 
	private String senderName;
	private String receiverName;
	
	
	public String getSenderName() {
		if(userSender!=null)
			return userSender.getUserName();
		else
			return senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public String getReceiverName() {
		if(userReceiver!=null)
			return userReceiver.getUserName();
		else
			return receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	private Date messageTime;

	private String messageTitle;

	private String messageContent;

	public Message() {
	}

	public Message(int messageId, User userSender, User userReceiver, Date messageTime,
			String messageTitle, String messageContent) {
		this.messageId = messageId;
		this.userSender = userSender;
		this.userReceiver = userReceiver;
		this.messageTime = messageTime;
		this.messageTitle = messageTitle;
		this.messageContent = messageContent;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public Date getMessageTime() {
		return this.messageTime;
	}

	public void setMessageTime(Date messageTime) {
		this.messageTime = messageTime;
	}

	public String getMessageTitle() {
		return this.messageTitle;
	}

	public void setMessageTitle(String messageTitle) {
		this.messageTitle = messageTitle;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public User getUserSender() {
		return userSender;
	}

	public void setUserSender(User userSender) {
		this.userSender = userSender;
	}

	public User getUserReceiver() {
		return userReceiver;
	}

	public void setUserReceiver(User userReceiver) {
		this.userReceiver = userReceiver;
	}

	public Boolean getMessageStatus() {
		return messageStatus;
	}

	public void setMessageStatus(Boolean messageStatus) {
		this.messageStatus = messageStatus;
	}

	
	public String getMessageRead() {
		if(messageStatus){
			messageRead = "已读";
		}
		else{
			messageRead = "未读";
		}
		return messageRead;
	}

	public void setMessageRead(String messageRead) {
		this.messageRead = messageRead;
	}

	@Override
	public Integer getId() {
		return getMessageId();
	}

	@Override
	public void setId(Integer id) {
		setMessageId(id);
	}
	
}
