package org.lch.attendance.domain;

// Generated 2012-5-2 16:56:18 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Resource generated by hbm2java
 */
@Entity
public class Resource extends BaseEntity implements java.io.Serializable {

	private Integer resourceId;

	private Integer resourceParentId;
	
	private Resource resource;

	private String resourceName;

	private String resourceType;

	private String resourceValue;

	private String resourceDesc;

	private boolean resourceEnabled;

	private boolean resourceIsLeaf;

	private Set<Resource> resources = new HashSet<Resource>(0);

	private Set<Role> roles = new HashSet<Role>(0);

	public Resource() {
	}

	public Resource(String resourceName, String resourceType,
			String resourceValue, boolean resourceEnabled,
			boolean resourceIsLeaf) {
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.resourceValue = resourceValue;
		this.resourceEnabled = resourceEnabled;
		this.resourceIsLeaf = resourceIsLeaf;
	}

	public Resource(Resource resource, String resourceName,
			String resourceType, String resourceValue, String resourceDesc,
			boolean resourceEnabled, boolean resourceIsLeaf,
			Set<Resource> resources, Set<Role> roles) {
		this.resource = resource;
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.resourceValue = resourceValue;
		this.resourceDesc = resourceDesc;
		this.resourceEnabled = resourceEnabled;
		this.resourceIsLeaf = resourceIsLeaf;
		this.resources = resources;
		this.roles = roles;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getResourceValue() {
		return this.resourceValue;
	}

	public void setResourceValue(String resourceValue) {
		this.resourceValue = resourceValue;
	}

	public String getResourceDesc() {
		return this.resourceDesc;
	}

	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc;
	}

	public boolean isResourceEnabled() {
		return this.resourceEnabled;
	}

	public void setResourceEnabled(boolean resourceEnabled) {
		this.resourceEnabled = resourceEnabled;
	}

	public boolean isResourceIsLeaf() {
		return this.resourceIsLeaf;
	}

	public void setResourceIsLeaf(boolean resourceIsLeaf) {
		this.resourceIsLeaf = resourceIsLeaf;
	}

	public Set<Resource> getResources() {
		return this.resources;
	}

	public void setResources(Set<Resource> resources) {
		this.resources = resources;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}
	
	@Override
	public Integer getId() {
		return this.resourceId;
	}

	@Override
	public void setId(Integer id) {
		this.resourceId = id;
	}
	
	/**
	 * Transient，用于页面显示整理菜单时使用
	 */
	private List<Resource> sortedChildResources = null;

	public List<Resource> getSortedChildResources() {
		return sortedChildResources;
	}

	public void setSortedChildResources(List<Resource> sortedChildResources) {
		this.sortedChildResources = sortedChildResources;
	}

	public Integer getResourceParentId() {
		return resourceParentId;
	}

	public void setResourceParentId(Integer resourceParentId) {
		this.resourceParentId = resourceParentId;
	}
}
