package org.lch.attendance.domain;

// Generated 2012-5-2 16:56:18 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.lch.attendance.model.BaseEntity;

/**
 * Role generated by hbm2java
 */
@Entity
public class Role extends BaseEntity implements java.io.Serializable {

	private Integer roleId;

	private String roleName;

	private boolean roleEnabled;

	private String roleDesc;

	private Set<User> users = new HashSet<User>(0);

	private Set<Resource> resources = new HashSet<Resource>(0);

	public Role() {
	}

	public Role(String roleName, boolean roleEnabled) {
		this.roleName = roleName;
		this.roleEnabled = roleEnabled;
	}

	public Role(String roleName, boolean roleEnabled, String roleDesc,
			Set<User> users, Set<Resource> resources) {
		this.roleName = roleName;
		this.roleEnabled = roleEnabled;
		this.roleDesc = roleDesc;
		this.users = users;
		this.resources = resources;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public boolean isRoleEnabled() {
		return this.roleEnabled;
	}

	public void setRoleEnabled(boolean roleEnabled) {
		this.roleEnabled = roleEnabled;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Resource> getResources() {
		return this.resources;
	}

	public void setResources(Set<Resource> resources) {
		this.resources = resources;
	}
	
	@Override
	public Integer getId() {
		return this.roleId;
	}

	@Override
	public void setId(Integer id) {
		this.roleId = id;
	}
}
