package org.lch.attendance.domain;

// Generated 2012-5-2 16:56:18 by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.lch.attendance.dao.WeekDao;
import org.lch.attendance.model.BaseEntity;
import org.lch.attendance.util.DateUtil;

/**
 * Week generated by hbm2java
 */
@Entity
public class Week extends BaseEntity implements java.io.Serializable {

	private Integer weekId;

	private Clas clas;

	private Department department;

	private User user;
	
	private Year year;

	private String yearName;
	
	private Date weekTime;

	private String deptName;
	
	private String clasGrade;
	
	private String clasName;
	
	private String userName;
	
	private Integer weekNum;
	
//	@javax.annotation.Resource
//	private WeekDao weekDao;
//TODO
	public Integer getWeekNum() {
//		int begin = DateUtil.getWeekNum(getWeekDepend());
//		int now = DateUtil.getWeekNum(getWeekTime());
//		if(now > begin){
//			return now-begin+1;
//		}else{
//			weekDao.getSuperHibernateTemplate().fin
//		}
		return weekNum;
//		return now-begin+1;
	}

	public void setWeekNum(Integer weekNum) {
		this.weekNum = weekNum;
	}

	private Set<Detail> details = new HashSet<Detail>(0);

	public Week() {
	}

	public Week(Clas clas, Department department, User user, Date weekTime,Year year) {
		this.clas = clas;
		this.department = department;
		this.user = user;
		this.weekTime = weekTime;
		this.year = year;
	}

	public Week(Clas clas, Department department, User user, Date weekTime,Year year,
			Set<Detail> details) {
		this.clas = clas;
		this.department = department;
		this.user = user;
		this.weekTime = weekTime;
		this.details = details;
		this.year = year;
	}

	public Integer getWeekId() {
		return this.weekId;
	}

	public void setWeekId(Integer weekId) {
		this.weekId = weekId;
	}

	public Clas getClas() {
		return this.clas;
	}

	public void setClas(Clas clas) {
		this.clas = clas;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getWeekTime() {
		return this.weekTime;
	}

	public void setWeekTime(Date weekTime) {
		this.weekTime = weekTime;
	}

	public Set<Detail> getDetails() {
		return this.details;
	}

	public void setDetails(Set<Detail> details) {
		this.details = details;
	}

	@Override
	public Integer getId() {
		return weekId;
	}

	@Override
	public void setId(Integer id) {
		setWeekId(id);
	}

	public String getDeptName() {
		if(department!=null)
			return department.getDeptName();
		else
			return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getClasGrade() {
		if(clas!=null)
			return clas.getClasGrade();
		else
			return clasGrade;
	}

	public void setClasGrade(String clasGrade) {
		this.clasGrade = clasGrade;
	}

	public String getClasName() {
		if(clas!=null)
			return clas.getClasName();
		else 
			return clasName;
	}

	public void setClasName(String clasName) {
		this.clasName = clasName;
	}

	public String getUserName() {
		if(user!=null)
			return user.getUserName();
		else
			return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Year getYear() {
		return year;
	}

	public void setYear(Year year) {
		this.year = year;
	}

	public String getYearName() {
		if(year!=null)
			return year.getYearName();
		else
			return yearName;
	}

	public void setYearName(String yearName) {
		this.yearName = yearName;
	}
}
